spring:
  application:
    name: hr

  datasource:
    url: jdbc:mysql://localhost:3310/miksa
    dbname: miksa
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: tue
    hibernate:
      ddl-auto: update

