version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-miksa
    environment:
      MYSQL_ROOT_PASSWORD: cande34Pa
      MYSQL_DATABASE: miksa
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - miksa-network

volumes:
  mysql-data:

networks:
  miksa-network:
    driver: bridge
